# Generated by Django 3.2.9 on 2021-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_thematic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
