# Generated by Django 3.2.9 on 2021-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_thematic_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_title', models.CharField(blank=True, max_length=250, null=True)),
                ('var_date', models.CharField(blank=True, max_length=250, null=True)),
                ('var_imageUrl', models.CharField(blank=True, max_length=250, null=True)),
                ('var_link', models.CharField(blank=True, max_length=250, null=True)),
                ('var_website', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
